// Points
export const FETCH_POINTS_SUCCESS = 'FETCH_POINTS_SUCCESS';
export const FETCH_POINTS_FAILURE = 'FETCH_POINTS_FAILURE';
export const FETCH_POINT_SUCCESS = 'FETCH_POINT_SUCCESS';
export const FETCH_POINT_FAILURE = 'FETCH_POINT_FAILURE';

// Loading
export const START_API_CALL= 'START_API_CALL';
export const END_API_CALL = 'END_API_CALL';

// Search Bar
export const CHANGE_SEARCH_BAR_TERM = 'CHANGE_SEARCH_BAR_TERM';
export const CHANGE_SEARCH_BAR_TYPE = 'CHANGE_SEARCH_BAR_TYPE';
export const SET_COMPLETE_SEARCH = 'SET_COMPLETE_SEARCH';

// Report
export const FETCH_REPORT_DATA_FAILURE = 'FETCH_REPORT_DATA_FAILURE';
export const FETCH_REPORT_DATA_SUCCESS = 'FETCH_REPORT_DATA_SUCCESS';
export const CHANGE_REPORT_TYPE = 'CHANGE_REPORT_TYPE';
