export const FETCH_POINTS_SUCCESS = 'FETCH_POINTS_SUCCESS';
export const FETCH_POINTS_FAILURE = 'FETCH_POINTS_FAILURE';
export const FETCH_POINT_SUCCESS = 'FETCH_POINT_SUCCESS';
export const FETCH_POINT_FAILURE = 'FETCH_POINT_FAILURE';
export const START_API_CALL= 'START_API_CALL';
export const END_API_CALL = 'END_API_CALL';
