export const FETCH_POINTS_SUCCESS = 'FETCH_POINTS_SUCCESS';
export const FETCH_POINTS_FAILURE = 'FETCH_POINTS_FAILURE';
export const FETCH_POINT_SUCCESS = 'FETCH_POINT_SUCCESS';
export const FETCH_POINT_FAILURE = 'FETCH_POINT_FAILURE';
